# Demo 1

In [2]:
# import libraries
import pandas as pd
import numpy as np

In [3]:
# create a pandas data frame
simple_df = pd.DataFrame({'column1': [1, 2, 3], 'column2': ['a', 'b', 'c']})

In [4]:
simple_df

   column1 column2
0        1       a
1        2       b
2        3       c

In [5]:
# create a numpy array
arr = np.array([1,2,3])

In [6]:
arr

array([1, 2, 3])

In [7]:
# read in csv file using pandas
airbnb = pd.read_csv('datasci_day3_anchorage_airbnb_data.csv')

In [8]:
# subset columns and create a new dataframe
airbnb_room_price = airbnb[['room_id', 'price']]

In [9]:
# write out a csv file using pandas
airbnb_room_price.to_csv('airbnb_rooms.csv')

# Demo 2

In [10]:
# describe a dataframe
airbnb.describe()

,room_id,survey_id,host_id,country,borough,reviews,overall_satisfaction,accommodates,bedrooms,bathrooms,price,minstay,latitude,longitude
count,9.320000e+02,932.0,9.320000e+02,0.0,0.0,932.000000,932.000000,932.000000,932.000000,0.0,932.000000,0.0,932.000000,932.000000
mean,1.289253e+07,1380.0,5.326474e+07,NaN,NaN,13.166309,2.770923,4.173820,1.590129,NaN,132.698498,NaN,61.162649,-149.766141
std,5.361241e+06,0.0,4.035356e+07,NaN,NaN,23.766796,2.412339,2.527155,0.942737,NaN,109.791758,NaN,0.086286,0.243623
min,6.712400e+04,1380.0,7.595900e+04,NaN,NaN,0.000000,0.000000,1.000000,0.000000,NaN,10.000000,NaN,60.942883,-149.981284
25%,8.818983e+06,1380.0,1.784022e+07,NaN,NaN,0.000000,0.000000,2.000000,1.000000,NaN,75.000000,NaN,61.143438,-149.905289
50%,1.391084e+07,1380.0,4.667786e+07,NaN,NaN,4.000000,4.500000,4.000000,1.000000,NaN,100.000000,NaN,61.183564,-149.859743
75%,1.764421e+07,1380.0,8.254043e+07,NaN,NaN,15.000000,5.000000,6.000000,2.000000,NaN,159.000000,NaN,61.207656,-149.770522
max,1.946811e+07,1380.0,1.365677e+08,NaN,NaN,190.000000,5.000000,16.000000,6.000000,NaN,1300.000000,NaN,61.424795,-149.107107

In [11]:
# dataframe shape
airbnb.shape

(932, 20)

In [12]:
# subset rows
airbnb.head()

,room_id,survey_id,host_id,room_type,country,city,borough,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,bathrooms,price,minstay,name,created_date,latitude,longitude,location
0,13362174,1380,1170579,Entire home/apt,NaN,Anchorage,NaN,South Addition,2,0.0,6,3,NaN,350,NaN,Park Strip Luxury w/ Rooftop Deck,5/5/17 0:00,61.211724,-149.898093,0101000020E610000087F8872DBDBC62C09FE3A3C5199B...
1,18485287,1380,28021789,Entire home/apt,NaN,Anchorage,NaN,Eagle River Valley,0,0.0,12,4,NaN,395,NaN,Luxurious Family Friendly Home!,1/21/17 0:00,61.323455,-149.535686,0101000020E61000009A5DF75624B162C0255D33F966A9...
2,15453778,1380,99136999,Entire home/apt,NaN,Anchorage,NaN,South Addition,3,5.0,10,4,NaN,425,NaN,Luxury Downtown Mountain View Home!,4/6/17 0:00,61.211908,-149.888389,0101000020E610000009A4C4AE6DBC62C061E124CD1F9B...
3,18445418,1380,65113356,Entire home/apt,NaN,Anchorage,NaN,Fairview,1,0.0,10,4,NaN,480,NaN,Historic Home in Heart of Anchorage,2/25/17 0:00,61.206739,-149.863625,0101000020E61000004260E5D0A2BB62C064E76D6C769A...
4,16798620,1380,111675486,Entire home/apt,NaN,Anchorage,NaN,Hillside East,2,0.0,11,3,NaN,350,NaN,Mountain Chalet With Sweeping Views,1/8/17 0:00,61.119465,-149.719996,0101000020E610000007280D350AB762C021020EA14A8F...

In [13]:
# filter
airbnb.loc[airbnb.neighborhood == 'Girdwood'].head()

,room_id,survey_id,host_id,room_type,country,city,borough,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,bathrooms,price,minstay,name,created_date,latitude,longitude,location
7,9709665,1380,1328153,Entire home/apt,NaN,Anchorage,NaN,Girdwood,19,4.5,10,4,NaN,205,NaN,4BR 2BA Private House w/ Large Deck,3/15/17 0:00,60.957365,-149.154464,0101000020E6100000198D7C5EF1A462C0E3AAB2EF8A7A...
14,11065272,1380,57433061,Entire home/apt,NaN,Anchorage,NaN,Girdwood,0,0.0,7,2,NaN,225,NaN,a Girdwood Garden inn,4/28/17 0:00,60.956825,-149.117548,0101000020E6100000BAF605F4C2A362C0637FD93D797A...
19,2032064,1380,8091825,Entire home/apt,NaN,Anchorage,NaN,Girdwood,2,0.0,6,2,NaN,250,NaN,Cozy Condo at the Base of Alyeska,3/19/17 0:00,60.961569,-149.109402,0101000020E6100000BE839F3880A362C078EC67B1147B...
32,8381677,1380,44170116,Entire home/apt,NaN,Anchorage,NaN,Girdwood,3,5.0,6,2,NaN,229,NaN,Snowbird Condo 1D 2 Bedroom,2/20/17 0:00,60.959102,-149.114734,0101000020E6100000A837A3E6ABA362C09CC3B5DAC37A...
37,535857,1380,2633440,Entire home/apt,NaN,Anchorage,NaN,Girdwood,20,5.0,6,2,NaN,225,NaN,Beautiful condo Alyeska slopeside!!,5/16/17 0:00,60.960408,-149.109930,0101000020E61000002D5BEB8B84A362C08C683BA6EE7A...

In [14]:
# value counts
airbnb.neighborhood.value_counts()

South Addition          101
Girdwood                 99
Sand Lake                84
Spenard                  57
Turnagain                53
Fairview                 49
Abbott Loop              48
Taku/Campbell            41
University Area          34
Northeast                34
Campbell Park            30
North Star               28
Russian Jack Park        27
Rabbit Creek             26
Downtown                 22
Eagle River Valley       19
Midtown                  17
Scenic Foothills         17
Airport Heights          14
Mid-Hillside             13
Chugiak                  13
Bayshore/Klatt           13
Hillside East            12
Old Seward/Oceanview     12
Rogers Park              12
Tudor Area               11
Huffman/O'Malley         10
Eagle River               8
Mountain View             7
South Fork                7
Bear Valley               5
Government Hill           5
Birchwood                 3
Basher                    1
Name: neighborhood, dtype: int64

In [15]:
# mean/min/max/median/std/count
airbnb.bedrooms.std()

0.94273705349907866

In [16]:
# corr
airbnb.corr()

,room_id,survey_id,host_id,country,borough,reviews,overall_satisfaction,accommodates,bedrooms,bathrooms,price,minstay,latitude,longitude
room_id,1.000000,NaN,0.590128,NaN,NaN,-0.476520,-0.403566,0.018702,0.007092,NaN,-0.022201,NaN,0.091819,-0.070518
survey_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
host_id,0.590128,NaN,1.000000,NaN,NaN,-0.285304,-0.269877,-0.023448,-0.030983,NaN,-0.022758,NaN,0.067177,-0.063096
country,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
borough,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reviews,-0.476520,NaN,-0.285304,NaN,NaN,1.000000,0.461861,-0.084819,-0.104865,NaN,-0.151807,NaN,-0.002279,-0.051746
overall_satisfaction,-0.403566,NaN,-0.269877,NaN,NaN,0.461861,1.000000,-0.005971,-0.025272,NaN,-0.149383,NaN,-0.060597,0.015395
accommodates,0.018702,NaN,-0.023448,NaN,NaN,-0.084819,-0.005971,1.000000,0.772028,NaN,0.549195,NaN,-0.087416,0.124371
bedrooms,0.007092,NaN,-0.030983,NaN,NaN,-0.104865,-0.025272,0.772028,1.000000,NaN,0.544264,NaN,0.011988,0.018887
bathrooms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,-0.022201,NaN,-0.022758,NaN,NaN,-0.151807,-0.149383,0.549195,0.544264,NaN,1.000000,NaN,-0.144444,0.145188
minstay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,0.091819,NaN,0.067177,NaN,NaN,-0.002279,-0.060597,-0.087416,0.011988,NaN,-0.144444,NaN,1.000000,-0.615421
longitude,-0.070518,NaN,-0.063096,NaN,NaN,-0.051746,0.015395,0.124371,0.018887,NaN,0.145188,NaN,-0.615421,1.000000

# Joining/Aggregating

In [17]:
# join
neighborhood_area = pd.DataFrame({
    'neighborhood': ['South Addison', 'Girdwood', 'Sand Lake', 'Spenard', 'Turnagain', 'Fairview'],
    'area': [1, 2, 2, 1, 1, 2]})

airbnb_area = pd.merge(airbnb, neighborhood_area, on = 'neighborhood', how = 'left')

In [18]:
# sorting
airbnb.sort_values(['host_id', 'room_id'], ascending=False)

,room_id,survey_id,host_id,room_type,country,city,borough,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,bathrooms,price,minstay,name,created_date,latitude,longitude,location
20,19468109,1380,136567670,Entire home/apt,NaN,Anchorage,NaN,North Star,0,0.0,4,0,NaN,227,NaN,szs,3/12/17 0:00,61.198560,-149.886429,0101000020E61000003BA759A05DBC62C09A25016A6A99...
728,19452990,1380,136408886,Entire home/apt,NaN,Anchorage,NaN,Eagle River Valley,0,0.0,3,3,NaN,64,NaN,19436 Highland Ridge Dr,2/14/17 0:00,61.302442,-149.518122,0101000020E6100000D2AA967494B062C0EA77616BB6A6...
223,19393350,1380,135960605,Private room,NaN,Anchorage,NaN,Abbott Loop,0,0.0,2,1,NaN,125,NaN,A quiet and comfortable place,2/1/17 0:00,61.141228,-149.833543,0101000020E6100000E9995E62ACBA62C0C6A354C21392...
36,19390972,1380,135948239,Entire home/apt,NaN,Anchorage,NaN,Abbott Loop,0,0.0,9,4,NaN,250,NaN,"Modern, Comfortable, Convenient. Sleeps 9",1/15/17 0:00,61.145843,-149.821631,0101000020E6100000274C18CD4ABA62C0DEACC1FBAA92...
228,19391045,1380,135886683,Private room,NaN,Anchorage,NaN,Downtown,0,0.0,2,1,NaN,100,NaN,"Anchorage Downtown Bed and Breakfast, room 1A",5/28/17 0:00,61.219442,-149.893815,0101000020E61000009335EA219ABC62C036AFEAAC169C...
365,19384974,1380,135886683,Private room,NaN,Anchorage,NaN,Downtown,0,0.0,2,1,NaN,100,NaN,"Anchorage Downtown Bed and Breakfast, room 1B",5/18/17 0:00,61.220339,-149.895120,0101000020E6100000DBBFB2D2A4BC62C045847F11349C...
378,19378148,1380,135827574,Private room,NaN,Anchorage,NaN,University Area,0,0.0,1,0,NaN,85,NaN,Nice private bedroom,1/2/17 0:00,61.186436,-149.804926,0101000020E610000067B62BF4C1B962C006668522DD97...
686,19353407,1380,135623406,Entire home/apt,NaN,Anchorage,NaN,Spenard,0,0.0,2,1,NaN,90,NaN,Spenard Apartment,3/13/17 0:00,61.193837,-149.922731,0101000020E61000002C80290387BD62C09CE09BA6CF98...
287,19345617,1380,135548215,Entire home/apt,NaN,Anchorage,NaN,Sand Lake,2,0.0,4,1,NaN,90,NaN,Cozy Cottage Style Home near Airport,4/29/17 0:00,61.155981,-149.926363,0101000020E61000002FA704C4A4BD62C010E6762FF793...
805,19305489,1380,135200941,Private room,NaN,Anchorage,NaN,Northeast,0,0.0,4,2,NaN,61,NaN,Single family home,1/24/17 0:00,61.209080,-149.769873,0101000020E610000059A2B3CCA2B862C0B41F2922C39A...
783,19293225,1380,135102952,Entire home/apt,NaN,Anchorage,NaN,Sand Lake,0,0.0,4,2,NaN,51,NaN,cozy and quaint space near the airport,3/18/17 0:00,61.146753,-149.946983,0101000020E6100000C6DB4AAF4DBE62C081CB63CDC892...
698,19252302,1380,134818976,Entire home/apt,NaN,Anchorage,NaN,Chugiak,0,0.0,9,2,NaN,90,NaN,Peaceful Alaskan housing,5/11/17 0:00,61.369332,-149.507764,0101000020E6100000C2C2499A3FB062C0E2AE5E4546AF...
443,19215719,1380,134437111,Private room,NaN,Anchorage,NaN,Spenard,0,0.0,2,1,NaN,70,NaN,Cozy Spenard Room,3/6/17 0:00,61.198251,-149.911127,0101000020E61000001570CFF327BD62C01CB3EC496099...
170,19178723,1380,134133883,Entire home/apt,NaN,Anchorage,NaN,Downtown,4,5.0,2,1,NaN,165,NaN,Panoramic views in downtown Anchorage,1/24/17 0:00,61.220382,-149.891465,0101000020E6100000EB909BE186BC62C04450357A359C...
145,19161139,1380,133985115,Entire home/apt,NaN,Anchorage,NaN,Taku/Campbell,0,0.0,6,2,NaN,175,NaN,GRAND OPENING discount! Creekside Executive Su...,4/30/17 0:00,61.153334,-149.871875,0101000020E610000066666666E6BB62C0B4AED172A093...
603,19157237,1380,133949437,Entire home/apt,NaN,Anchorage,NaN,Spenard,0,0.0,8,2,NaN,120,NaN,Quiet Duplex close to Airport,2/20/17 0:00,61.180324,-149.924154,0101000020E6100000F6CE68AB92BD62C08A5759DB1497...
863,19144466,1380,133821580,Private room,NaN,Anchorage,NaN,South Addition,0,0.0,2,1,NaN,160,NaN,City Garden Bed & Breakfast,1/16/17 0:00,61.212911,-149.910490,0101000020E6100000B9AAECBB22BD62C0B5FAEAAA409B...
219,19143866,1380,133821580,Private room,NaN,Anchorage,NaN,South Addition,0,0.0,2,1,NaN,130,NaN,City Garden Bed & Breakfast,2/22/17 0:00,61.213037,-149.910497,0101000020E610000065C39ACA22BD62C042EBE1CB449B...
844,19142455,1380,133821580,Private room,NaN,Anchorage,NaN,South Addition,0,0.0,2,1,NaN,190,NaN,City Garden Bed & Breakfast,2/6/17 0:00,61.212165,-149.910167,0101000020E6100000C05C8B1620BD62C08C2D0439289B...
586,19134900,1380,133742302,Entire home/apt,NaN,Anchorage,NaN,University Area,0,0.0,4,2,NaN,125,NaN,Lake-front 2 bedroom Condo near Hospitals,3/1/17 0:00,61.182997,-149.774957,0101000020E6100000CD599F72CCB862C0102219726C97...
766,19124209,1380,133658639,Entire home/apt,NaN,Anchorage,NaN,Sand Lake,3,5.0,4,2,NaN,72,NaN,Ground floor apartment close to Airport,2/27/17 0:00,61.163887,-149.952609,0101000020E6100000029CDEC57BBE62C0AA9ECC3FFA94...
91,19335206,1380,133446345,Entire home/apt,NaN,Anchorage,NaN,Airport Heights,0,0.0,8,3,NaN,199,NaN,Great Alaskan Townhome,3/25/17 0:00,61.213891,-149.808396,0101000020E6100000F3C64961DEB962C051F4C0C7609B...
184,19101539,1380,133446345,Entire home/apt,NaN,Anchorage,NaN,Russian Jack Park,2,0.0,8,3,NaN,149,NaN,Convenient Adventure Townhouse,3/26/17 0:00,61.212177,-149.807029,0101000020E61000008E3D7B2ED3B962C050FBAD9D289B...
558,19042801,1380,132911045,Entire home/apt,NaN,Anchorage,NaN,Campbell Park,0,0.0,4,1,NaN,125,NaN,Campbell Creek Retreat,5/29/17 0:00,61.180391,-149.830857,0101000020E6100000E3546B6196BA62C012BF620D1797...
324,19178007,1380,132869788,Entire home/apt,NaN,Anchorage,NaN,Old Seward/Oceanview,0,0.0,14,5,NaN,425,NaN,New! Luxury Living! Incredible Views! Sleeps 14+,1/23/17 0:00,61.089237,-149.836533,0101000020E6100000CBA0DAE0C4BA62C0EC4B361E6C8B...
658,19040540,1380,132869788,Entire home/apt,NaN,Anchorage,NaN,Old Seward/Oceanview,1,0.0,3,1,NaN,98,NaN,"2-Story Tiny Guest House with Mnt View, Large ...",3/27/17 0:00,61.090163,-149.838396,0101000020E61000001C23D923D4BA62C0952710768A8B...
706,19040111,1380,132869788,Entire home/apt,NaN,Anchorage,NaN,Old Seward/Oceanview,1,0.0,4,1,NaN,89,NaN,"New! 2-story Alaska Cabin, by Wildlife boardwalk!",3/27/17 0:00,61.088829,-149.836935,0101000020E610000017BCE82BC8BA62C0DBF7A8BF5E8B...
657,19038647,1380,132869788,Entire home/apt,NaN,Anchorage,NaN,Old Seward/Oceanview,2,0.0,4,0,NaN,98,NaN,Studio near Bird Sanctuary and Wildlife Boardw...,5/7/17 0:00,61.089766,-149.837520,0101000020E6100000DF37BEF6CCBA62C07825C9737D8B...
285,19000450,1380,132563043,Entire home/apt,NaN,Anchorage,NaN,Fairview,7,4.5,2,0,NaN,95,NaN,Urban Cabin,4/5/17 0:00,61.209520,-149.874507,0101000020E6100000F0A31AF6FBBB62C0D0ED258DD19A...
51,19000323,1380,132560901,Entire home/apt,NaN,Anchorage,NaN,Sand Lake,3,3.5,11,4,NaN,212,NaN,Sand lake Comfort zone,1/8/17 0:00,61.155434,-149.962119,0101000020E610000087FBC8ADC9BE62C0DE57E542E593...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,9709665,1380,1328153,Entire home/apt,NaN,Anchorage,NaN,Girdwood,19,4.5,10,4,NaN,205,NaN,4BR 2BA Private House w/ Large Deck,3/15/17 0:00,60.957365,-149.154464,0101000020E6100000198D7C5EF1A462C0E3AAB2EF8A7A...
161,7717644,1380,1328153,Entire home/apt,NaN,Anchorage,NaN,South Addition,44,4.5,6,2,NaN,175,NaN,2BR 1BA Prime Downtown Anchorage *KING BEDS*,1/25/17 0:00,61.210813,-149.904853,0101000020E61000000056478EF4BC62C02C499EEBFB9A...
66,7636493,1380,1328153,Entire home/apt,NaN,Anchorage,NaN,South Addition,11,5.0,2,1,NaN,190,NaN,King Bed & Jacuzzi Tub,5/25/17 0:00,61.209680,-149.904152,0101000020E61000009ED32CD0EEBC62C0095053CBD69A...
43,3677979,1380,1328153,Entire home/apt,NaN,Anchorage,NaN,South Addition,52,5.0,8,2,NaN,230,NaN,"2BR 2BA Anchorage Inlet Getaway, Lots of Light!",5/10/17 0:00,61.210757,-149.904274,0101000020E6100000F01307D0EFBC62C09833DB15FA9A...
28,6613604,1380,1207149,Entire home/apt,NaN,Anchorage,NaN,Sand Lake,34,5.0,6,3,NaN,300,NaN,"Modern, bright remodel for groups",1/18/17 0:00,61.143356,-149.970100,0101000020E610000030BB270F0BBF62C0BAD7497D5992...
362,18980051,1380,1170579,Private room,NaN,Anchorage,NaN,South Addition,0,0.0,2,1,NaN,100,NaN,Chic Designer Suite on the Park Strip,1/2/17 0:00,61.213277,-149.896834,0101000020E61000001C7E37DDB2BC62C097FE25A94C9B...
377,18977242,1380,1170579,Private room,NaN,Anchorage,NaN,South Addition,0,0.0,2,1,NaN,100,NaN,Designer Luxury on the Park Strip,4/15/17 0:00,61.212889,-149.897383,0101000020E6100000909F8D5CB7BC62C0CD565EF23F9B...
0,13362174,1380,1170579,Entire home/apt,NaN,Anchorage,NaN,South Addition,2,0.0,6,3,NaN,350,NaN,Park Strip Luxury w/ Rooftop Deck,5/5/17 0:00,61.211724,-149.898093,0101000020E610000087F8872DBDBC62C09FE3A3C5199B...
425,198146,1380,966980,Private room,NaN,Anchorage,NaN,Taku/Campbell,16,5.0,1,1,NaN,75,NaN,"Bright, quiet condo - lots of light",3/12/17 0:00,61.152243,-149.865947,0101000020E610000038A27BD6B5BB62C0C005D9B27C93...
455,13210919,1380,887316,Private room,NaN,Anchorage,NaN,Northeast,8,5.0,2,1,NaN,73,NaN,Cozy room in Anchorage,5/28/17 0:00,61.196014,-149.768237,0101000020E610000078D2C26595B862C071C79BFC1699...
782,11364434,1380,880217,Entire home/apt,NaN,Anchorage,NaN,Sand Lake,2,0.0,2,1,NaN,58,NaN,"Clean, quiet and comfortable rooms-Great locat...",4/1/17 0:00,61.135478,-149.935338,0101000020E61000009816F549EEBD62C0EBA9D5575791...
559,5263073,1380,880217,Entire home/apt,NaN,Anchorage,NaN,Sand Lake,22,5.0,6,3,NaN,129,NaN,Spacious House with Lots of Light - Great Loca...,4/6/17 0:00,61.136727,-149.936623,0101000020E6100000CE35CCD0F8BD62C077BD34458091...
487,851770,1380,873211,Private room,NaN,Anchorage,NaN,Scenic Foothills,85,5.0,4,2,NaN,79,NaN,Private Room(s)/Bath East Anchorage,4/6/17 0:00,61.183875,-149.756519,0101000020E6100000AF79556735B862C0A8C64B378997...
388,6855528,1380,858658,Private room,NaN,Anchorage,NaN,Tudor Area,21,5.0,2,1,NaN,90,NaN,Private room in midtown home (#3),4/15/17 0:00,61.183258,-149.842012,0101000020E6100000DE5A26C3F1BA62C07D5D86FF7497...
440,2420653,1380,858658,Private room,NaN,Anchorage,NaN,Tudor Area,62,5.0,2,1,NaN,70,NaN,Private room in midtown home (#2),5/27/17 0:00,61.182827,-149.841883,0101000020E6100000DE019EB4F0BA62C0B4E908E06697...
483,179328,1380,858658,Private room,NaN,Anchorage,NaN,Tudor Area,62,5.0,2,1,NaN,70,NaN,Private room in midtown home (#1),2/8/17 0:00,61.182984,-149.840557,0101000020E6100000902DCBD7E5BA62C07BD80B056C97...
665,147921,1380,714693,Entire home/apt,NaN,Anchorage,NaN,Sand Lake,19,5.0,5,2,NaN,99,NaN,"comfy, clean, & family friendly apt",3/6/17 0:00,61.140393,-149.943883,0101000020E610000003081F4A34BE62C02ECBD765F891...
672,18705823,1380,614550,Entire home/apt,NaN,Anchorage,NaN,South Addition,1,0.0,6,2,NaN,100,NaN,Prime Downtown/Coastal Trail Access at the Lagoon,4/30/17 0:00,61.210965,-149.908944,0101000020E6100000A73CBA1116BD62C0E2CCAFE6009B...
740,18256522,1380,546807,Entire home/apt,NaN,Anchorage,NaN,Eagle River,6,5.0,10,3,NaN,76,NaN,Bright and Cozy Three Bedroom,4/30/17 0:00,61.323972,-149.556076,0101000020E6100000E542E55FCBB162C0EC681CEA77A9...
368,86019,1380,472124,Private room,NaN,Anchorage,NaN,Old Seward/Oceanview,0,0.0,2,2,NaN,99,NaN,Jarvi Homestay Bed and Breakfast,2/9/17 0:00,61.092179,-149.841322,0101000020E6100000F86C1D1CECBA62C062307F85CC8B...
12,12981839,1380,354837,Entire home/apt,NaN,Anchorage,NaN,Abbott Loop,0,0.0,3,2,NaN,225,NaN,Quiet hideaway,5/5/17 0:00,61.157202,-149.851084,0101000020E6100000C34483143CBB62C0D26EF4311F94...
317,4567899,1380,353572,Entire home/apt,NaN,Anchorage,NaN,Spenard,0,0.0,7,3,NaN,475,NaN,A Comfortable Stay in Turnagain,2/22/17 0:00,61.192502,-149.926613,0101000020E61000008D614ED0A6BD62C01135D1E7A398...
439,2671261,1380,353572,Private room,NaN,Anchorage,NaN,Turnagain,58,5.0,2,1,NaN,80,NaN,The Music Legends Room @ A Comfortable Stay,4/7/17 0:00,61.194204,-149.925212,0101000020E6100000BC3B32569BBD62C04E603AADDB98...
481,583343,1380,353572,Private room,NaN,Anchorage,NaN,Turnagain,113,5.0,2,1,NaN,80,NaN,The Falconry Room @ A Comfortable Stay,3/14/17 0:00,61.193922,-149.926932,0101000020E6100000B5334C6DA9BD62C0CAFCA36FD298...
357,570220,1380,353572,Private room,NaN,Anchorage,NaN,Turnagain,82,5.0,3,1,NaN,114,NaN,The Countryside Room @ A Comfortable Stay,5/10/17 0:00,61.193852,-149.925795,0101000020E61000009CF9D51CA0BD62C0D1217024D098...
605,5020149,1380,342702,Entire home/apt,NaN,Anchorage,NaN,Spenard,0,0.0,6,2,NaN,102,NaN,Northern Stay,3/11/17 0:00,61.180028,-149.921278,0101000020E6100000C710001C7BBD62C0A12E52280B97...
786,67124,1380,330458,Entire home/apt,NaN,Anchorage,NaN,Fairview,81,4.5,2,1,NaN,45,NaN,Garden Level Executive Midtown Anchorage Condo,1/31/17 0:00,61.207269,-149.876260,0101000020E6100000605969520ABC62C0C03C64CA879A...
647,13477776,1380,209742,Entire home/apt,NaN,Anchorage,NaN,Fairview,28,5.0,2,1,NaN,115,NaN,"Cozy, comfortable and minutes from downtown",4/19/17 0:00,61.207140,-149.877366,0101000020E6100000EA93DC6113BC62C0C3D84290839A...
588,2908852,1380,209742,Entire home/apt,NaN,Anchorage,NaN,Fairview,62,5.0,5,2,NaN,135,NaN,Comfortable home in convenient location!,3/26/17 0:00,61.203725,-149.882170,0101000020E6100000657094BC3ABC62C055302AA9139A...
485,17996414,1380,75959,Private room,NaN,Anchorage,NaN,Spenard,2,0.0,4,1,NaN,60,NaN,Roosevelt Manor -- a retro Spenard studio,2/10/17 0:00,61.181949,-149.919193,0101000020E6100000CA3670076ABD62C01C45D61A4A97...

In [19]:
# groupby
airbnb.groupby(['neighborhood', 'room_type'])['bedrooms'].mean()

neighborhood          room_type
Abbott Loop           Entire home/apt    2.333333
                      Private room       1.043478
                      Shared room        1.000000
Airport Heights       Entire home/apt    2.222222
                      Private room       1.000000
Basher                Entire home/apt    1.000000
Bayshore/Klatt        Entire home/apt    2.500000
                      Private room       1.000000
Bear Valley           Entire home/apt    2.000000
                      Private room       1.333333
Birchwood             Entire home/apt    2.000000
                      Private room       3.000000
Campbell Park         Entire home/apt    1.866667
                      Private room       1.066667
Chugiak               Entire home/apt    2.500000
                      Private room       1.142857
Downtown              Entire home/apt    1.615385
                      Private room       0.888889
Eagle River           Entire home/apt    2.142857
                      Private room       0.000000
Eagle River Valley    Entire home/apt    2.000000
                      Private room       1.400000
Fairview              Entire home/apt    1.558824
                      Private room       1.133333
Girdwood              Entire home/apt    1.776316
                      Private room       1.000000
                      Shared room        1.000000
Government Hill       Entire home/apt    2.000000
                      Private room       1.000000
                      Shared room        1.000000
                                           ...
Northeast             Private room       1.000000
Old Seward/Oceanview  Entire home/apt    1.714286
                      Private room       1.600000
Rabbit Creek          Entire home/apt    1.428571
                      Private room       1.083333
Rogers Park           Entire home/apt    2.166667
                      Private room       1.000000
Russian Jack Park     Entire home/apt    2.400000
                      Private room       1.000000
Sand Lake             Entire home/apt    1.963636
                      Private room       1.000000
                      Shared room        1.000000
Scenic Foothills      Entire home/apt    1.666667
                      Private room       1.181818
South Addition        Entire home/apt    1.716418
                      Private room       1.117647
South Fork            Entire home/apt    2.333333
                      Private room       1.000000
Spenard               Entire home/apt    1.891892
                      Private room       1.000000
Taku/Campbell         Entire home/apt    1.923077
                      Private room       0.928571
                      Shared room        1.000000
Tudor Area            Entire home/apt    2.166667
                      Private room       1.400000
Turnagain             Entire home/apt    2.185185
                      Private room       1.090909
                      Shared room        1.000000
University Area       Entire home/apt    2.333333
                      Private room       1.045455
Name: bedrooms, Length: 75, dtype: float64